--- 
id: basics
name: 01 Remix基礎
summary: A typical workflow in Remix
level: 1
tags: 
  - Remix
steps:
  - name: 画面インターフェース 
    path: interface_introduction
  - name: ワークスペース 
    path: workspaces
  - name: ロード & コンパイル
    path: load_and_compile
  - name: Remix VM へのデプロイ
    path: deploy_to_the_remixvm
  - name: デプロイ関数の操作
    path: interacting
  - name: 外部ネットワークへのデプロイ
    path: deploy_injected