---
id: opcodesdebug
name: 03 オペコードのデバッグ
summary: Using the Debugger, we'll check out what the CODECOPY opcode does and how it is used by the EVM during contract creation.
level: 3 
tags: 
  - Remix
  - Debugging
  - EVM
  - Opcodes
steps:
  - name: 1. 導入
    path: 1_intro
  - name: 2. メモリ
    path: 2_memory
  - name: 3. コードコピー
    path: 3_codecopy
  - name: 4. CODECOPYとデプロイ
    path: 4_Deployment_and_CODECOPY
  - name: 5. CODECOPYとデバッグ
    path: 5_Debugger_and_CODECOPY
  - name: 6. CODECOPYとチェック
    path: 6_Checking_CODECOPY
  - name: 7. 戻り値とデータ
    path: 7_returnAndStore
  - name: 8. オフセット参照
    path: 8_findTheOffset
