--- 
id: er721Auction
name: 01 NFTオークション
summary: Learn how to write an ERC721 (NFT) auction contract. Developed by the p2p learning platform https://dacade.org.
level: 2
tags: 
  - Solidity
  - Tokens
  - NFT
steps:
  - name: コントラクト セットアップ 
    path: auction-contract-setup
  - name: 開始時の処理と入札関数
    path: auction-start-bid
  - name: 引き出しと終了関数
    path: auction-withdraw-end